# Generated by Django 5.2.9 on 2025-12-25 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("LC", "LeetCode"), ("CF", "Codeforces")], max_length=2
                    ),
                ),
                ("source_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("difficulty", models.CharField(max_length=10)),
                ("pattern_tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("source", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="UserProblemRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difficulty", models.FloatField(default=0.0)),
                ("stability", models.FloatField(default=0.0)),
                ("last_review_date", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateTimeField(blank=True, null=True)),
                ("total_reviews", models.IntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.problem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "Again"), (2, "Hard"), (3, "Good"), (4, "Easy")]
                    ),
                ),
                ("time_spent", models.DurationField(blank=True, null=True)),
                ("user_insight", models.TextField(blank=True)),
                ("commit_hash", models.CharField(blank=True, max_length=64)),
                ("solution_snapshot", models.TextField(blank=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.userproblemrecord",
                    ),
                ),
            ],
        ),
    ]
