# Generated by Django 5.2.9 on 2025-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproblemrecord",
            name="current_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="rating",
            field=models.IntegerField(choices=[(1, "Fail"), (2, "Pass")]),
        ),
    ]
