# Generated by Django 5.2.9 on 2025-12-25 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewlog",
            name="commit_hash",
        ),
        migrations.RemoveField(
            model_name="reviewlog",
            name="solution_snapshot",
        ),
        migrations.RemoveField(
            model_name="userproblemrecord",
            name="file_path",
        ),
    ]
