# Generated by Django 5.2.9 on 2025-12-31 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_reviewlog_commit_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userproblemrecord",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userproblemrecord",
            unique_together={("user", "problem", "course")},
        ),
    ]
