# Generated by Django 5.1.4 on 2025-12-31 12:31

from django.db import migrations

def migrate_records(apps, schema_editor):
    UserProblemRecord = apps.get_model('core', 'UserProblemRecord')
    Course = apps.get_model('core', 'Course')
    
    # Iterate over all records that have no course
    for record in UserProblemRecord.objects.filter(course__isnull=True):
        problem = record.problem
        user = record.user
        
        # Find courses that contain this problem for this user
        courses = Course.objects.filter(user=user, problems=problem)
        
        if courses.exists():
            # Create a record for each course
            for i, course in enumerate(courses):
                if i == 0:
                    # Update the existing record for the first course
                    record.course = course
                    record.save()
                else:
                    # Create new records for subsequent courses
                    # We need to copy all fields
                    UserProblemRecord.objects.create(
                        user=user,
                        problem=problem,
                        course=course,
                        difficulty=record.difficulty,
                        stability=record.stability,
                        last_review_date=record.last_review_date,
                        next_review_date=record.next_review_date,
                        total_reviews=record.total_reviews,
                        current_level=record.current_level
                    )
        # If no course, leave it as None (General)

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userproblemrecord_course_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_records, reverse_migrate),
    ]
