# Generated by Django 5.2.9 on 2025-12-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20251231_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userproblemrecord",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
    ]
