# Generated by Django 5.2.9 on 2026-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_course_is_paused_userproblemrecord_is_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("cpp", "C++")],
                default="python",
                max_length=20,
            ),
        ),
    ]
