# Generated by Django 5.2.9 on 2026-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="practice_directory",
            field=models.CharField(
                blank=True,
                help_text="Base directory for practice files",
                max_length=512,
            ),
        ),
    ]
