# Generated by Django 5.2.9 on 2026-01-01 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_course_practice_directory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="practice_directory",
        ),
    ]
