# Generated by Django 5.2.9 on 2026-07-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_course_practice_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("cpp", "C++"), ("c", "C")],
                default="python",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="source",
            field=models.CharField(
                choices=[
                    ("LC", "LeetCode"),
                    ("CF", "Codeforces"),
                    ("CS", "CSES"),
                    ("MN", "Manual"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
